### PR TITLE
Fix accessibility problems and video link in README.md

### PR DESCRIPTION
**Pull request by Saitama2016**
I was able to change the Brand Orange to the Brand Blue color for the accessibility issue and attached the link to your demo video on your README.md file.

### CODE REVIEW

**Review by Mcgurk-Adam — CHANGES_REQUESTED** [review]
Hey, great PR!! Just one thing, we can't change the background-color to #fff, because that is not in line with the brand design standards (to be open sourced shortly). That background color needs to stay #f3f4f5. Change that one little thing, and I'll approve it!

**Comment by Mcgurk-Adam** [comment]
Also, I love what you did with adding the aria-roles!!! I always forget about those accessibility checks

**Comment by Saitama2016** [comment]
Thanks for the feedback, I'll make the changes now.

**Comment by Saitama2016** [comment]
I pushed the changes to the Background. You can review it again at your earliest convenience.

**Review by Mcgurk-Adam — APPROVED** [review]
Looks great!! Merging now! Will update at the URL this evening

**Pull request merged**
